"""
LiteLLM Proxy Manager — OpenHands + Langfuse Observability Integration

This module manages a LiteLLM Proxy subprocess that:
  - Acts as a transparent forwarding proxy for all LLM calls
  - Sends observability/tracing data to Langfuse via the ``langfuse_otel`` callback
  - Collects: prompt/completion/total tokens, cost, latency, model name,
    full request/response payloads

Architecture::

    OpenHands ──→ LiteLLM Proxy (port 4000) ──→ LLM Provider (OpenAI, etc.)
                           │
                           ├── langfuse_otel callback
                           │
                           └──→ Langfuse Cloud (OTLP)

Usage::

    from openhands.app_server.services.litellm_proxy_manager import (
        LangfuseLiteLLMIntegration,
    )

    integration = LangfuseLiteLLMIntegration()
    integration.start()

    # Now configure OpenHands LLM:
    #   base_url=http://localhost:4000
    #   api_key=<any-nonempty-value>

    integration.stop()

Official references:
  - https://langfuse.com/integrations/gateways/litellm
  - https://docs.litellm.ai/docs/observability/langfuse_otel_integration
"""

from __future__ import annotations

import logging
import os
import signal
import subprocess
import sys
import tempfile
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import IO

# ---------------------------------------------------------------------------
# Hardcoded Langfuse credentials (per KAN-20 requirements).
# These are embedded in the module and injected as environment variables
# when the LiteLLM proxy subprocess starts so that the ``langfuse_otel``
# callback can authenticate with Langfuse.
# ---------------------------------------------------------------------------
LANGFUSE_SECRET_KEY = "sk-lf-2adf9dc1-8582-4d1d-8eeb-1ef5b5c4e1e8"
LANGFUSE_PUBLIC_KEY = "pk-lf-6c9b4b03-80c5-4c5d-8565-b681f02d2c71"
LANGFUSE_BASE_URL = "https://us.cloud.langfuse.com"
LANGFUSE_PROJECT = "my-llm-project"

LITELLM_PROXY_HOST = "0.0.0.0"
LITELLM_PROXY_PORT = 4000

# Master key for LiteLLM proxy API auth.  Clients must send this as the
# ``Authorization: Bearer`` header when calling proxy API endpoints
# (health-check endpoints are exempt).  OpenHands uses this same value
# as the LLM ``api_key`` when routing through the proxy.
LITELLM_PROXY_MASTER_KEY = "sk-l0g79haCLaZaGXpwJ6rwWautjihHrGyngLXhgkQoPYXX93DKXzfUNwza2TFEW5xs"

logger = logging.getLogger(__name__)
_DEBUG_PREFIX = "[LITELLM-LANGFUSE]"


def _info(msg: str, *args, **kwargs):
    logger.info(f"{_DEBUG_PREFIX} {msg}", *args, **kwargs)


def _warn(msg: str, *args, **kwargs):
    logger.warning(f"{_DEBUG_PREFIX} {msg}", *args, **kwargs)


def _error(msg: str, *args, **kwargs):
    logger.error(f"{_DEBUG_PREFIX} {msg}", *args, **kwargs)


# ---------------------------------------------------------------------------
# LiteLLM Proxy config generation
# ---------------------------------------------------------------------------

DEFAULT_PROXY_CONFIG_YAML = r"""# ============================================================================
# LiteLLM Proxy Configuration — Langfuse Observability
# ============================================================================
# Generated by: openhands/app_server/services/litellm_proxy_manager.py
#
# This config enables the ``langfuse_otel`` callback which sends LLM
# observability data (tokens, cost, latency, payloads) to Langfuse via
# the OpenTelemetry protocol.
#
# Official references:
#   https://langfuse.com/integrations/gateways/litellm
#   https://docs.litellm.ai/docs/observability/langfuse_otel_integration
# ============================================================================

# ── Model routing ──────────────────────────────────────────────────────────
model_list:
  # OpenCode Zen model — the primary model used by this integration.
  - model_name: "deepseek-v4-flash-free"
    litellm_params:
      model: "openai/deepseek-v4-flash-free"
      api_key: "sk-l0g79haCLaZaGXpwJ6rwWautjihHrGyngLXhgkQoPYXX93DKXzfUNwza2TFEW5xs"
      api_base: "https://opencode.ai/zen/v1"

  # Passthrough catch-all — forwards any other request to the provider
  # inferred from the model name.
  - model_name: "*"
    litellm_params:
      model: "*"

# ── Callbacks — Observability ──────────────────────────────────────────────
# The ``langfuse_otel`` callback sends traces to Langfuse via the OpenTelemetry
# protocol (OTLP). Credentials are injected from environment variables by the
# proxy manager before startup.
#
# Why ``langfuse_otel`` instead of ``langfuse``?
#   - ``langfuse`` (legacy) — sends data via the direct Langfuse API.
#   - ``langfuse_otel`` (recommended) — uses the OpenTelemetry protocol, which
#     is vendor-neutral and captures richer data (spans, timing, metadata).
#     Both Langfuse and LiteLLM official docs recommend this callback.
#     See: https://langfuse.com/integrations/gateways/litellm
litellm_settings:
  callbacks: ["langfuse_otel"]
  set_verbose: true

# ── General settings ───────────────────────────────────────────────────────
general_settings:
  # Master key — required by LiteLLM proxy for API auth.
  # Clients must send ``Authorization: Bearer <master_key>`` when calling
  # the proxy. Health-check endpoints (``/health/*``) are exempt.
  master_key: "sk-l0g79haCLaZaGXpwJ6rwWautjihHrGyngLXhgkQoPYXX93DKXzfUNwza2TFEW5xs"
  pass_through: true
"""


def _resolve_litellm_binary() -> str:
    """Return the path to the ``litellm`` CLI binary."""
    # 1. Check PATH
    litellm_path = os.popen("which litellm 2>/dev/null").read().strip()
    if litellm_path and os.path.isfile(litellm_path):
        return litellm_path
    # 2. Check common install locations
    candidates = [
        "/home/openhands/.local/bin/litellm",
        os.path.join(os.path.dirname(sys.executable), "litellm"),
        "/usr/local/bin/litellm",
    ]
    for candidate in candidates:
        if os.path.isfile(candidate):
            return candidate
    # 3. Fallback — try running via python -m
    if (
        os.popen(
            f'{sys.executable} -c "import litellm.proxy.proxy_cli" 2>/dev/null'
        ).close()
        is None
    ):
        return f"{sys.executable} -m litellm"
    # 4. Last resort: assume it's in PATH even if not found
    return "litellm"


# ---------------------------------------------------------------------------
# Manager
# ---------------------------------------------------------------------------


@dataclass
class LangfuseLiteLLMIntegration:
    """Manages a LiteLLM Proxy subprocess configured for Langfuse
    observability.

    Lifecycle::

        integration = LangfuseLiteLLMIntegration()
        integration.start()   # launches proxy subprocess
        ...
        integration.stop()    # terminates proxy subprocess

    While running, point OpenHands at ``http://localhost:4000``::

        export LITE_LLM_API_URL=http://localhost:4000
        # or in your LLM settings:
        #   model: gpt-4o
        #   base_url: http://localhost:4000
        #   api_key: <your-openai-key>
    """

    host: str = LITELLM_PROXY_HOST
    port: int = LITELLM_PROXY_PORT
    config_path: Path | None = None

    _process: subprocess.Popen | None = field(default=None, repr=False)
    _log_file: IO | None = field(default=None, repr=False)
    _start_lock: threading.Lock = field(default_factory=threading.Lock, repr=False)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def start(
        self,
        timeout: float = 60.0,
        extra_models: list[dict] | None = None,
    ) -> bool:
        """Start the LiteLLM Proxy subprocess.

        Args:
            timeout: Max seconds to wait for the proxy to become ready.
            extra_models: Optional list of model dicts to append to the
                proxy ``model_list``. Each dict should conform to the
                LiteLLM proxy model config format.

        Returns:
            ``True`` if the proxy started successfully, ``False`` otherwise.
        """
        with self._start_lock:
            if self._process is not None:
                _info("Proxy is already running (pid=%d)", self._process.pid)
                return True

            if not self._check_installation():
                return False

            # Kill any stale proxy on the target port before starting
            self._ensure_port_free()

            config_path = self._write_config(extra_models)
            if config_path is None:
                return False

            env = self._build_env()

            _info(
                "Starting LiteLLM proxy on %s:%d (config=%s)",
                self.host,
                self.port,
                config_path,
            )
            _info("Langfuse tracing enabled: project=%s", LANGFUSE_PROJECT)

            try:
                litellm_bin = _resolve_litellm_binary()
                cmd = [
                    litellm_bin,
                    "--config",
                    str(config_path),
                    "--port",
                    str(self.port),
                    "--host",
                    self.host,
                ]

                # Redirect proxy logs to a temp file for debugging
                log_path = Path(tempfile.gettempdir()) / "litellm_proxy.log"
                self._log_file = open(log_path, "w", buffering=1)
                self._log_file.write(
                    f"# LiteLLM proxy started at {time.strftime('%Y-%m-%dT%H:%M:%S')}\n"
                    f"# Config: {config_path}\n"
                    f"# Cmd: {' '.join(cmd)}\n\n"
                )
                self._log_file.flush()

                _info("Starting subprocess: %s", " ".join(cmd))
                self._process = subprocess.Popen(
                    cmd,
                    env=env,
                    stdout=self._log_file,
                    stderr=subprocess.STDOUT,
                    stdin=subprocess.DEVNULL,
                    start_new_session=True,
                )
                _info(
                    "LiteLLM proxy subprocess started (pid=%d)", self._process.pid
                )

            except FileNotFoundError as exc:
                _error("LiteLLM binary not found: %s", exc)
                self._cleanup()
                return False
            except Exception as exc:
                _error("Failed to start LiteLLM proxy: %s", exc)
                self._cleanup()
                return False

        # Wait for the proxy to become responsive
        ready = self._wait_ready(timeout)

        if not ready:
            _error(
                "LiteLLM proxy did not become ready within %.0fs. "
                "Check logs: %s",
                timeout,
                self._log_file.name if self._log_file else "(none)",
            )
            # Dump the tail of the proxy log to aid debugging
            self._dump_proxy_log()
            self.stop()
            return False

        _info("LiteLLM proxy is ready on %s:%d", self.host, self.port)
        return True

    def stop(self, timeout: float = 10.0) -> None:
        """Stop the LiteLLM Proxy subprocess gracefully."""
        with self._start_lock:
            proc = self._process
            if proc is None:
                return

            _info("Stopping LiteLLM proxy (pid=%d)...", proc.pid)

            try:
                # Send SIGTERM first
                os.killpg(os.getpgid(proc.pid), signal.SIGTERM)
                proc.wait(timeout=timeout)
            except Exception:
                # Force kill
                try:
                    os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
                except Exception:
                    pass

            self._cleanup()
            _info("LiteLLM proxy stopped")

    @property
    def is_running(self) -> bool:
        """Check if the proxy subprocess is still running."""
        proc = self._process
        if proc is None:
            return False
        ret = proc.poll()
        return ret is None

    @property
    def proxy_url(self) -> str:
        """Return the base URL of the running proxy."""
        host = self.host if self.host != "0.0.0.0" else "localhost"
        return f"http://{host}:{self.port}"

    @staticmethod
    def get_required_env_vars() -> dict[str, str]:
        """Return the environment variables needed for Langfuse + LiteLLM
        integration.

        These must be set before starting the proxy so that the
        ``langfuse_otel`` callback can authenticate with Langfuse.
        """
        otel_host = LANGFUSE_BASE_URL
        return {
            "LANGFUSE_PUBLIC_KEY": LANGFUSE_PUBLIC_KEY,
            "LANGFUSE_SECRET_KEY": LANGFUSE_SECRET_KEY,
            "LANGFUSE_OTEL_HOST": otel_host,
            "LANGFUSE_PROJECT": LANGFUSE_PROJECT,
            "OTEL_EXPORTER_OTLP_ENDPOINT": f"{otel_host}/api/public/otel",
            "OTEL_EXPORTER_OTLP_HEADERS": (
                "Authorization=Basic "
                + _basic_auth_token(LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY)
            ),
            "OTEL_IGNORE_CONTEXT_PROPAGATION": "true",
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _check_installation(self) -> bool:
        """Verify that litellm is installed and the CLI is available."""
        try:
            binary = _resolve_litellm_binary()
            _info("LiteLLM binary resolved to: %s", binary)
            import litellm  # noqa: F401 — ensure the package is importable

            return True
        except ImportError as exc:
            _error(
                "LiteLLM is not installed. Install it with: "
                "pip install 'litellm>=1.40.0'"
            )
            _error("Import error: %s", exc)
            return False

    @staticmethod
    def _ensure_port_free() -> None:
        """Kill any existing process listening on the target proxy port.

        This prevents failures when uvicorn reloads and the old proxy
        subprocess was orphaned (still holding the port).
        """
        import socket

        host = LITELLM_PROXY_HOST
        port = LITELLM_PROXY_PORT

        # Quick check: is the port already in use?
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            s.settimeout(1)
            result = s.connect_ex((host, port))
            s.close()
            if result != 0:
                return  # port is free
        except Exception:
            s.close()
            return

        # Port is occupied — try to find and kill the process
        _warn("Port %d is already in use — attempting to free it", port)
        try:
            import psutil

            for conn in psutil.net_connections():
                if conn.laddr.port == port and conn.status == "LISTEN":
                    pid = conn.pid
                    if pid:
                        _info("Killing process %d holding port %d", pid, port)
                        proc = psutil.Process(pid)
                        proc.terminate()
                        proc.wait(timeout=5)
            return
        except ImportError:
            # psutil not available — fall back to fuser
            pass
        except Exception:
            pass

        # Fallback: try fuser
        try:
            import subprocess as _subprocess

            _subprocess.run(
                ["fuser", "-k", f"{port}/tcp"],
                capture_output=True,
                timeout=5,
            )
        except Exception:
            _warn(
                "Could not free port %d automatically. "
                "Please ensure no other process is using it.",
                port,
            )

    def _dump_proxy_log(self) -> None:
        """Log the tail of the proxy subprocess log for debugging.

        Called when startup fails to give the user immediate visibility
        into what went wrong without requiring a separate ``cat``.
        """
        if self._log_file is None:
            return
        log_path = self._log_file.name
        try:
            import subprocess as _subprocess

            result = _subprocess.run(
                ["tail", "-30", log_path],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.stdout:
                _error("--- Last 30 lines of proxy log (%s) ---", log_path)
                for line in result.stdout.rstrip().splitlines():
                    _error("  | %s", line)
                _error("--- End of proxy log ---")
        except Exception as exc:
            _error("Could not read proxy log %s: %s", log_path, exc)

    def _write_config(self, extra_models: list[dict] | None = None) -> Path | None:
        """Write the proxy config YAML to a temporary file and return its path."""
        try:
            import yaml
        except ImportError:
            _error(
                "PyYAML is required. Install it with: pip install pyyaml"
            )
            return None

        config = yaml.safe_load(DEFAULT_PROXY_CONFIG_YAML)

        # Append any extra models
        if extra_models:
            config.setdefault("model_list", []).extend(extra_models)

        # Write to a stable temp path
        config_dir = Path(tempfile.gettempdir()) / "openhands-litellm"
        config_dir.mkdir(parents=True, exist_ok=True)
        config_path = config_dir / "litellm_config.yaml"

        try:
            with open(config_path, "w") as f:
                yaml.dump(config, f, default_flow_style=False, sort_keys=False)
            _info("Proxy config written to: %s", config_path)
            self.config_path = config_path
            return config_path
        except Exception as exc:
            _error("Failed to write proxy config: %s", exc)
            return None

    def _build_env(self) -> dict[str, str]:
        """Build the environment for the proxy subprocess.

        Merges the current process env with the explicit Langfuse env vars
        needed by the ``langfuse_otel`` callback.
        """
        env = os.environ.copy()
        env.update(self.get_required_env_vars())
        # Enable verbose logging from the proxy for debugging
        env.setdefault("LITELLM_LOG", "DEBUG")
        return env

    def _wait_ready(self, timeout: float = 60.0) -> bool:
        """Poll the proxy health endpoint until it responds or times out."""
        import urllib.request
        import urllib.error
        import socket as _socket

        deadline = time.monotonic() + timeout

        # Try multiple endpoints — some LiteLLM versions respond on different
        # paths before they report full readiness.
        probe_urls = [
            f"{self.proxy_url}/health/liveliness",
            f"{self.proxy_url}/health/ready",
            f"{self.proxy_url}/health",
            f"{self.proxy_url}/v1/models",
        ]

        _info("Waiting for proxy to be ready (timeout=%.0fs)...", timeout)
        while time.monotonic() < deadline:
            # Check the process first
            if self._process and self._process.poll() is not None:
                _error(
                    "Proxy process exited prematurely (retcode=%d)",
                    self._process.returncode,
                )
                return False

            # Try connecting to the port first (cheapest check)
            try:
                s = _socket.socket(_socket.AF_INET, _socket.SOCK_STREAM)
                s.settimeout(1)
                s.connect((self.host if self.host != "0.0.0.0" else "127.0.0.1", self.port))
                s.close()
            except Exception:
                time.sleep(0.5)
                continue

            # Port is accepting connections — try the probe endpoints
            for url in probe_urls:
                try:
                    req = urllib.request.Request(url)
                    with urllib.request.urlopen(req, timeout=2) as resp:
                        if resp.status in (200, 302, 301):
                            return True
                except (urllib.error.URLError, ConnectionRefusedError, OSError):
                    pass

            time.sleep(0.5)

        return False

    def _cleanup(self) -> None:
        """Clean up resources (log file, process reference)."""
        if self._log_file is not None:
            try:
                self._log_file.close()
            except Exception:
                pass
            self._log_file = None
        self._process = None


# ---------------------------------------------------------------------------
# Standalone helpers
# ---------------------------------------------------------------------------


def _basic_auth_token(public_key: str, secret_key: str) -> str:
    """Return a Base64-encoded Basic auth token: ``base64(pk:sk)``."""
    import base64

    raw = f"{public_key}:{secret_key}"
    return base64.b64encode(raw.encode()).decode()


def configure_openhands_for_proxy(proxy_url: str = f"http://localhost:{LITELLM_PROXY_PORT}") -> None:
    """Configure OpenHands to route all LLM calls through the given proxy.

    Sets environment variables that instruct the OpenHands LLM client to
    route ``openhands/``-prefixed model traffic through the proxy.

    * ``LITE_LLM_API_URL`` — proxy base URL (read by ``settings_router``).
    * ``LITE_LLM_API_KEY`` — proxy master key (read by ``_post_merge_llm_fixups``
      for LLM configs that route through the proxy and have no explicit key).

    For non-``openhands/`` models, you must set ``base_url`` and ``api_key``
    in the LLM settings to point at the proxy.
    """
    os.environ["LITE_LLM_API_URL"] = proxy_url
    os.environ["LITE_LLM_API_KEY"] = LITELLM_PROXY_MASTER_KEY
    _info("LITE_LLM_API_URL set to %s — OpenHands will route through proxy", proxy_url)


def check_trace_exists(
    proxy_url: str = f"http://localhost:{LITELLM_PROXY_PORT}",
    timeout: float = 10.0,
) -> bool:
    """Quick health check: verify the proxy is up and responds to a test
    request."""
    import urllib.request
    import urllib.error

    try:
        req = urllib.request.Request(f"{proxy_url}/health/readiness", method="GET")
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status == 200
    except Exception as exc:
        _warn("Proxy health check failed: %s", exc)
        return False
